import SatReadout
import AristotleQ1
import AristotleQ2
import AristotleQ3
import ToleranceIntent
import SatReadoutGeodesic
import SatReadoutNotGeodesic
import SatReadoutAtlas
#print axioms SatReadout.key_identity'
#print axioms SatReadout.no_midpoint
#print axioms StrictConcaveOn.subadditive_of_map_zero
#print axioms satPseudoMetricSpace_uniformity
#print axioms eps_midpoint_counterexample
#print axioms no_eps_midpoint_without_quadratic_bound_is_false
#print axioms ToleranceIntent.eoIntent_sound
#print axioms SatReadout.collinear_strict_wbtw
#print axioms SatReadout.satDist_breaks_geodesic
#print axioms satDist_not_geodesic
#print axioms satDist_not_length_metric
#print axioms SatReadout.atlas2_defect
#print axioms SatReadout.atlas2_collinear_strict
#print axioms SatReadout.hasDerivAt_atlasN_zero_of_sum_weight_eq_one
#print axioms SatReadout.atlasN_lt_weighted_asymptote
#print axioms SatReadout.atlasN_le_weighted_self
#print axioms SatReadout.atlasN_le_self_of_sum_weight_eq_one
#print axioms SatReadout.atlasN_sq_lower_weighted
#print axioms SatReadout.atlasN_defect
#print axioms SatReadout.atlasN_collinear_strict
#print axioms SatReadout.satAtlasNDist_no_midpoint
#print axioms SatReadout.satAtlasNDist_not_geodesic
